language: node_js
node_js:
  - 0.10
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "npm update -g" # update npm to recent version
  - "npm install -g bower"
  - "bower install"
script:
  - "./node_modules/karma/bin/karma start --no-auto-watch --single-run --reporters=dots --browsers PhantomJS"
  - "./node_modules/gulp/bin/gulp.js protractor:dist --browser=firefox"
